export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_STATUS = 'GET_PREFERENCES_STATUS';
export const CLEAR_PREFERENCES = 'CLEAR_PREFERENCES';
export const OPEN_MAP = 'OPEN_MAP';
export const OPEN_CONTACT = 'OPEN_CONTACT';
export const OPEN_INFO = 'OPEN_LIKES';
