export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_STATUS = 'GET_PREFERENCES_STATUS';

export const GET_DINE_DATA = 'GET_DINE_DATA';
export const GET_DINE_STATUS = 'GET_DINE_STATUS';

export const GET_PLAY_DATA = 'GET_PLAY_DATA';
export const GET_PLAY_STATUS = 'GET_PLAY_STATUS';

export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const GET_SERACH_STATUS = 'GET_SEARCH_STATUS';
