export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_STATUS = 'GET_PREFERENCES_STATUS';
export const CLEAR_PREFERENCES = 'CLEAR_PREFERENCES';
